AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  showyourgear

  Sample SAM Template for showyourgear

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  # 写真取得API
  GetPhotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis
      Handler: getphotos.Application::handleRequest
      Runtime: java17
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Photo:
          Type: Api
          Properties:
            Path: /photo
            Method: get
  # 写真登録API
  PostPhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis
      Handler: postphoto.Application::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Photo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /photos
            Method: post


  # 楽器判定API
  verifyGearFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis
      Handler: verifygear.Application::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Photo:
          Type: Api
          Properties:
            Path: /gear
            Method: post

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShowYourGearApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShowYourGear:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ShowYourGear.Arn
  ShowYourGearIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ShowYourGearRole.Arn
