version: '3'
services:
  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - 4566-4583:4566-4583
    environment:
      - AWS_ACCESS_KEY=dummy
      - AWS_SECRET_KEY=dummy
      - DEFAULT_REGION=ap-northeast-1
      - EDGE_PORT=4566
    volumes:
      - ./localstack/init:/docker-entrypoint-initaws.d
      - ./localstack/init/data:/tmp/init-data
      - ./localstack/localstack-mnt:/tmp/localstack/data